exp_name: nico_resvit18_multi_unshuffle_bf0.02_lr0.01
net: crop_conditioned_resnet18
dataset: NICO
#image_folder: /data2/wangtan/causal-invariant-attention/dataset/NICO/multi_classification
#cxt_dic_path: /data2/wangtan/causal-invariant-attention/dataset/NICO/label_file/Context_name2label.json
#class_dic_path: /data2/wangtan/causal-invariant-attention/dataset/NICO/label_file/Animal_name2label.json
image_folder: /data/cwen/NICO/multi_classification
cxt_dic_path: /data/cwen/NICO/Context_name2label.json
class_dic_path: /data/cwen/NICO/Animal_name2label.json
training_opt:
  seed: 0
  batch_size: 128
  lr: 0.05
  warm: 2
  epoch: 200
  milestones: [80, 120, 160]
  # milestones: [80, 140, 200]
  save_epoch: 20
  print_batch: 1
  mean: [0.52418953, 0.5233741, 0.44896784]
  std: [0.21851876, 0.2175944, 0.22552039]
variance_opt:
  balance_factor: 0.1
  training_dist: { 'cow': [ 'on_grass', 'on_snow' ],
                   'horse': [ 'on_snow', 'on_grass' ] }
  val_dist: { 'cow': ['in_river', 'lying', 'standing','eating','in_forest','on_grass','on_snow'],
              'horse': ['on_beach', 'aside_people', 'running','lying','on_grass','on_snow','in_forest'] }
  test_dist: { 'cow': ['in_river', 'lying', 'standing','eating','in_forest','on_grass','on_snow'],
               'horse': ['on_beach', 'aside_people', 'running','lying','on_grass','on_snow','in_forest'] }
  fusion_layer: 2
  crop_size: 120
  condition_activation: 'softmax'
  stop_gradient: True
  mode: 'chuan'
  env_type: 'baseline'
resume: False